name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: cd ./Project/GCC_LINUX && && mkdir ./obj && mkdir ./exe && make && cp ./exe/VirtualMeter ./ && make clean
 
